version: "3.9"

services:
  api:
    build: .
    container_name: ai-chat-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    command: flask run --host=0.0.0.0 --reload

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # persist models across restarts

volumes:
  ollama_data: